### ISSUE TITLE
Crash upon viewing hellbark lectern

### ISSUE THREAD

**Issue by TerraCraft25** [Yamahari/ILikeWood-1.15#14]
Playing on a modded server with some friends when one of them placed the hellbark lectern and crashed. In attempts to break it I joined him in an infinite crash loop when trying to log onto the server.
Crash report below:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 15/04/20 8:55 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.func_200662_C(WoodenLecternTileEntity.java:30) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47) ~[?:8.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_83_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:564) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:558) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.tileentity.LecternTileEntity.<init>(SourceFile:138) ~[?:?] {re:classloading}
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.<init>(WoodenLecternTileEntity.java:20) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at yamahari.ilikewood.registry.WoodenTileEntityTypes.lambda$null$5(WoodenTileEntityTypes.java:75) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at yamahari.ilikewood.registry.WoodenTileEntityTypes$$Lambda$4312/586367383.get(Unknown Source) ~[?:?] {}
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at yamahari.ilikewood.block.WoodenLecternBlock.func_196283_a_(WoodenLecternBlock.java:39) ~[?:1.15.2-2.2.2.0] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:178) ~[?:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:362) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:389) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.World.func_175625_s(World.java:691) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:51) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:39) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:58) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:112) ~[?:1.10.8-B72_1.15.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_115_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1450) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.43.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/1269819701.call(Unknown Source) [forge-1.15.2-31.1.43.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.func_200662_C(WoodenLecternTileEntity.java:30)
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47)
	at net.minecraftforge.eventbus.ASMEventHandler_83_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:564)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:558)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44)
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34)
	at net.minecraft.tileentity.LecternTileEntity.<init>(SourceFile:138)
	at yamahari.ilikewood.client.tileentity.WoodenLecternTileEntity.<init>(WoodenLecternTileEntity.java:20)
	at yamahari.ilikewood.registry.WoodenTileEntityTypes.lambda$null$5(WoodenTileEntityTypes.java:75)
	at yamahari.ilikewood.registry.WoodenTileEntityTypes$$Lambda$4312/586367383.get(Unknown Source)
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92)
	at yamahari.ilikewood.block.WoodenLecternBlock.func_196283_a_(WoodenLecternBlock.java:39)
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:178)
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:362)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:389)
	at net.minecraft.world.World.func_175625_s(World.java:691)
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:51)
	at mcp.mobius.waila.api.impl.DataAccessor.set(DataAccessor.java:39)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:58)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:112)
	at net.minecraftforge.eventbus.ASMEventHandler_115_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['TerraCraft25'/72483, l='MpServer', x=2071.33, y=63.50, z=2397.76]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -6553281700084237921
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (64,64,244), Chunk: (at 0,4,4 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5970452 game time, 3387884 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/1269819701.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 727679304 bytes (693 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.15.2_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.43.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.43
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.43-client.jar Minecraft {minecraft@1.15.2 DONE}
		doubledoors_1.15-2.0.jar Double Doors {doubledoors@2.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		inventoryprofiles-forge-1.15.2-0.2.1.jar Inventory Profiles {inventoryprofiles@0.2.1 DONE}
		Variant16x-1.15-v0.9.2.1_beta.jar Variant16x {variant16x@0.9.2.1_beta DONE}
		pamhc2trees-1.15.2-1.0.2.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		pamhc2crops-1.15.2-1.0.2.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		OptiForge-MC1.15.2-0.1.8.jar OptiForge {optiforge@0.1.8 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		extraboats-1.3.2-1.15.2.jar Extra Boats {extraboats@1.3.2 DONE}
		ShulkerTooltip-1.9.2.jar Shulker Tooltip {shulkertooltip@1.9.2 DONE}
		pamhc2foodcore-1.15.2-1.0.2.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		cyclepaintings_1.15-1.1.jar Cycle Paintings {cyclepaintings@1.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 DONE}
		DoubleSlabs-1.15-2.2.0.jar Double Slabs {doubleslabs@2.2.0 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		carpetstairsmod-1.4.2.jar Carpet Stairs Mod {carpetstairsmod@1.4.2.0 DONE}
		ilikewood-1.15.2-2.2.2.0.jar I Like Wood {ilikewood@1.15.2-2.2.2.0 DONE}
		forge-1.15.2-31.1.43-universal.jar Forge {forge@31.1.43 DONE}
		PassthroughSigns-1.15.2-2.3.3.jar Passthrough Signs {passthroughsigns@1.15.2-2.3.3 DONE}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 DONE}
		Variant16x-BiomesOPlenty-1.15-v0.9.2_beta_pre3.jar Variant16x: Biomes O' Plenty {variant16x_biomesoplenty@0.9.2_beta_pre3 DONE}
	Launched Version: 1.15.2-forge-31.1.43
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 25.20.100.6518, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6518
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Yamahari** [comment]
duplicated issue, i will close this one, look out for the other one :)
