### ISSUE TITLE
World Load Fatal Error w/ Thermal Expansion Stirling Dynamo

### ISSUE THREAD

**Issue by ghost** [Yamahari/ILikeWood-1.15#31]
`ILikeWood 1.16.5-6.1.1.0`
`Thermal Expansion 1.16.3-1.1.6`
`MC 1.16.5`
`Forge 36.0.14`

*Please let me know if you require any more information!*

Thermal Expansion is attempting to read the burn time of something from ILW for the Stirling Dynamo, which is causing a fatal datapack error that prevents the integrated server from starting. Note, this does not crash the game, but it prevents any datapacks from being loaded which *will* break mods.

<details>
    <summary>The relevant error (please expand!)</summary>

    [12:21:54] [Render thread/ERROR] [minecraft/SaveFormat]: Exception reading C:\_gdl\instances\Res Mechanica\saves\Test World v3\level.dat_old
    java.lang.NullPointerException: null
        at yamahari.ilikewood.item.WoodenBlockItem.getBurnTime(WoodenBlockItem.java:31) ~[ilikewood:1.16.5-6.1.1.0] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeItemStack.getBurnTime(IForgeItemStack.java:90) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraftforge.common.ForgeHooks.getBurnTime(ForgeHooks.java:1243) ~[forge:?] {re:mixin,re:classloading}
        at cofh.thermal.expansion.util.managers.dynamo.StirlingFuelManager.getEnergyFurnaceFuel(StirlingFuelManager.java:73) ~[thermal_expansion:1.1.6] {re:classloading}
        at cofh.thermal.expansion.util.managers.dynamo.StirlingFuelManager.getEnergy(StirlingFuelManager.java:62) ~[thermal_expansion:1.1.6] {re:classloading}
        at cofh.thermal.expansion.util.managers.dynamo.StirlingFuelManager.validFuel(StirlingFuelManager.java:49) ~[thermal_expansion:1.1.6] {re:classloading}
        at cofh.thermal.expansion.util.managers.dynamo.StirlingFuelManager.createConvertedRecipes(StirlingFuelManager.java:108) ~[thermal_expansion:1.1.6] {re:classloading}
        at cofh.thermal.expansion.util.managers.dynamo.StirlingFuelManager.refresh(StirlingFuelManager.java:91) ~[thermal_expansion:1.1.6] {re:classloading}
        at cofh.thermal.core.common.ThermalRecipeManagers.refreshServer(ThermalRecipeManagers.java:47) ~[thermal:1.1.6] {re:classloading}
        at cofh.thermal.core.event.TCoreCommonSetupEvents.idRemap(TCoreCommonSetupEvents.java:86) ~[thermal:1.1.6] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_438_TCoreCommonSetupEvents_idRemap_FMLModIdMappingEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.registries.GameData.fireRemapEvent(GameData.java:879) ~[forge:?] {re:classloading}
        at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:868) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.FMLWorldPersistenceHook.readData(FMLWorldPersistenceHook.java:121) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.WorldPersistenceHooks.lambda$handleWorldDataLoad$1(WorldPersistenceHooks.java:45) ~[forge:?] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242] {}
        at net.minecraftforge.fml.WorldPersistenceHooks.handleWorldDataLoad(WorldPersistenceHooks.java:45) ~[forge:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat.lambda$getReader$4(SaveFormat.java:202) ~[?:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat.func_237266_a_(SaveFormat.java:165) ~[?:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat.access$400(SaveFormat.java:63) ~[?:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat$LevelSave.func_237284_a_(SaveFormat.java:324) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.client.Minecraft.func_238181_a_(Minecraft.java:1672) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:AccessScreenButtons,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
        at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
        at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
        at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:APP:fabrication.mixins.json:j_experiments.no_set_window_pos.MixinWindow,pl:mixin:A}
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:notenoughcreativity.mixins.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,xf:fml:screenshotclipboard:coremodone,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.14.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

</summary>

**Comment by Yamahari** [comment]
Thanks for reporting, I'll have a look. Looks like either I forgot a map entry which causes null or thermal expansion is accessing something before initialization!

**Comment by Yamahari** [comment]
I cannot reproduce the error, what exactly did you do for this to happen? e.g. did you open an old world and what's the exact mod list? are you running optifine?

**Comment by SuomiIkuisesti** [comment]
@Yamahari same happened to me, and i was trying to open an old world. 

MODLIST:


torchslabmod-1.16.3_v1.6.18.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |NOSIGNATURE
		locks-1.16.2-2.5.2.jar                            |Locks                         |locks                         |2.5.2               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
		DoggyTalents-1.16.4-2.0.1.2.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.2             |DONE      |NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		Extra+Colours+1.6.1+(MC+1.16.4).jar               |Extra Colours                 |extra_colours                 |1.6.1               |DONE      |NOSIGNATURE
		mcw-paintings-1.0.0-mc1.16.4-5.jar                |Macaw's Paintings             |mcwpaintings                  |1.0.0               |DONE      |NOSIGNATURE
		WORLDMAP.jar                                      |Xaero's World Map             |xaeroworldmap                 |1.11.4              |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.80-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.76     |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.6.2.jar                |Decorative Blocks             |decorative_blocks             |1.6.2               |DONE      |NOSIGNATURE
		moreminecarts-1.02.jar                            |More Minecarts                |moreminecarts                 |1.02                |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |DONE      |NOSIGNATURE
		u_team_core-1.16.4-3.1.17.191.jar                 |U Team Core                   |uteamcore                     |3.1.17.191          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		bedspreads-forge-1.16.4-5.1.0.1.jar               |Bedspreads                    |bedspreads                    |1.16.4-5.1.0.1      |DONE      |NOSIGNATURE
		ironagefurniture-1.16.3-0.1.0.10.jar              |Iron Age Furniture            |ironagefurniture              |1.16.3-0.1.0.10     |DONE      |8d:b4:b9:c1:35:78:5a:8b:a4:56:3f:cc:92:94:c7:a8:bd:b3:cc:c9:f0:9f:e6:52:b6:7e:c1:9d:ed:7d:f2:c5
		Hwyla-Mod-1.16.3.jar                              |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.2.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.2               |DONE      |NOSIGNATURE
		Kiwi-1.16.4.jar                                   |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.26-universal.jar                |Forge                         |forge                         |36.0.26             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		scuba-gear-1.16.4-1.0.1.jar                       |Scuba Gear                    |scuba_gear                    |1.0.1               |DONE      |NOSIGNATURE
		supplementaries-0.9.16.jar                        |Supplementaries               |supplementaries               |0.9.16              |DONE      |NOSIGNATURE
		xercamusic-1.16.4-1.1.jar                         |Xerca's Music Maker Mod       |xercamusic                    |1.16.4-1.1          |DONE      |NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.1.jar           |Universal Mod Core            |universalmodcore              |1.0.1               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.26-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.4.jar                        |CoFH Core                     |cofh_core                     |1.1.4               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.4.jar               |Thermal Series                |thermal                       |1.1.4               |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.86.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.86           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		EditSign-Forge-1.16.4-2.2.0.jar                   |Edit Sign                     |editsign                      |2.2.0               |DONE      |NOSIGNATURE
		mcw-trapdors-1.0.0-mc1.16.4.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.0               |DONE      |NOSIGNATURE
		movingelevators-1.2.30-mc1.16.4.jar               |Moving Elevators              |movingelevators               |1.2.30              |DONE      |NOSIGNATURE
		masonry-1.16.3-0.3.6.jar                          |Masonry                       |masonry                       |NONE                |DONE      |NOSIGNATURE
		omgourd-1.16.3-1.1.0.jar                          |Oh My Gourd                   |omgourd                       |1.1.0               |DONE      |NOSIGNATURE
		tgcropesmod-1.16.2-1.1.0.jar                      |Ropes Mod                     |tgcropesmod                   |1.16.2-1.1.0        |DONE      |NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.0.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		car-1.16.4-1.1.4.jar                              |Ultimate Car Mod              |car                           |1.16.4-1.1.4        |DONE      |NOSIGNATURE
		plane-1.16.4-1.0.1.jar                            |Ultimate Plane Mod            |plane                         |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		JustARaftMod-1.16.3-1.1.3.jar                     |Just A Raft Mod               |justaraftmod                  |1.1.3               |DONE      |NOSIGNATURE
		MINIMAP.jar                                       |Xaero's Minimap               |xaerominimap                  |20.29.1             |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		horse_colors-1.16.4-1.5.2.jar                     |Realistic Horse Genetics      |horse_colors                  |1.16.4-1.5.2        |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.4.jar                |Thermal Expansion             |thermal_expansion             |1.1.4               |DONE      |NOSIGNATURE
		DoubleSlabs-1.16-3.4.10.jar                       |Double Slabs                  |doubleslabs                   |3.4.10              |DONE      |NOSIGNATURE
		backpacked-1.7.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.7.0               |DONE      |NOSIGNATURE
		backpacker-1.1.0-1.16.3.jar                       |Backpacker                    |backpacker                    |1.1.0               |DONE      |NOSIGNATURE
		skiing-1.16.5-1.1.0.jar                           |Skiing Mod                    |skiing                        |1.16.5-1.1.0        |DONE      |04:56:02:ea:42:d8:d7:8e:6b:75:10:21:73:49:e5:65:ed:4d:ea:36:f0:8d:bd:d5:b7:cd:9b:c2:00:75:28:be
		moarboats-1.16.3-8.0.0.0-beta3.jar                |Moar Boats                    |moarboats                     |1.16.3-8.0.0.0-beta3|DONE      |NOSIGNATURE
		usefulhats-1.9.3-1.16.2+.jar                      |Useful Hats                   |usefulhats                    |1.9.3-1.16.2+       |DONE      |NOSIGNATURE
		MatchlockGuns+1.16.2-2c.2.jar                     |Matchlock Guns Mod            |matchlockguns                 |1.16.2-2c.2         |DONE      |NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.0-dist.jar           |WorldEdit                     |worldedit                     |7.2.0+a51fa43       |DONE      |NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |DONE      |NOSIGNATURE
		cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		platos-1.4.4.jar                                  |Plato's Transporters          |platos                        |1.4.4               |DONE      |NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |NOSIGNATURE
		ilikewood-1.16.5-6.1.1.0.jar                      |I Like Wood                   |ilikewood                     |1.16.5-6.1.1.0      |DONE      |NOSIGNATURE
		Chisels-and-Bits-Mod-1.16.4.jar                   |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		joshxmas-1.16.4-1.0.0.jar                         |Joshua's Christmas Mod        |joshxmas

**Comment by Yamahari** [comment]
what version was the old world from?

**Comment by ghost** [comment]
> I cannot reproduce the error, what exactly did you do for this to happen? e.g. did you open an old world and what's the exact mod list? are you running optifine?

So sorry for not getting back to you. Optifine is present and it is an old world. I'll try and get a neat mods list to you in a moment.

The fact that someone else is having this issue without Optifine makes me think it isn't that. Not to mention that I'm not sure how the lighting pipeline relates to this, though, I'm not a mod maker!

I guess it's probably down to an old world or some other conflicting mod.

**Comment by ghost** [comment]
Okay, the crash still occurs without Optifine. Here is the list of my current mods: https://hatebin.com/bzznrnufdo

...I did forget to test with a new world though. Darn it, this pack takes a little bit to load up and into a world lol.

**Comment by SuomiIkuisesti** [comment]
> what version was the old world from?

1.16.4, but i updated to 1.16.5

**Comment by SuomiIkuisesti** [comment]
> what version was the old world from?

although it occures on me while the biomes o plenty plugin for i like wood was in my modpack

**Comment by Yamahari** [comment]
hm, than my initial suspect is not the reason :/
need to test this when I get the time then
Have you tried with a new world and without optifine? also do you habe optifine installed @SuomiIkuisesti or does it happen without that

**Comment by Yamahari** [comment]
also beware that between 1,16.4 and 1.16.5 i changed the way chests/barrels/lecterns work, that change breaks all existing chests/barrels and lecterns from my mod, see changelog https://www.curseforge.com/minecraft/mc-mods/i-like-wood/files/3171526
maybe that is the issue :thinking:

**Comment by SuomiIkuisesti** [comment]
> also beware that between 1,16.4 and 1.16.5 i changed the way chests/barrels/lecterns work, that change breaks all existing chests/barrels and lecterns from my mod, see changelog https://www.curseforge.com/minecraft/mc-mods/i-like-wood/files/3171526
> maybe that is the issue 🤔

i changed to 1.16.5 without placing any block/items on 1.16.4, and my problem starts when i have biomes o plenty plugin in my modpack

**Comment by SuomiIkuisesti** [comment]
> hm, than my initial suspect is not the reason :/
> need to test this when I get the time then
> Have you tried with a new world and without optifine? also do you habe optifine installed @SuomiIkuisesti or does it happen without that 

yes i got optifine for latest forge

**Comment by The-Brandolorian** [comment]
You can easily reproduce this as you get the exact same conflict with minecolonies but on any world load, even trying to make new ones.
Made a test pack with everything fully up to date including: ILW, ILW BOP, Minecolonies, Structurize, AutoRegLib, BOP, OTBYG and Quark. I can provide logs if necessary.

**Comment by Yamahari** [comment]
Heya, can you guys retry this with the latest plugin, I think I fixed it with https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/commit/b97715114cc4010df9402dd1579df6c26b89ed27
It was actually an issue with the plugin not the main mod

**Comment by ghost** [comment]
> Heya, can you guys retry this with the latest plugin, I think I fixed it with [Yamahari/ILikeWood-BiomesOPlenty-Plugin@b977151](https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/commit/b97715114cc4010df9402dd1579df6c26b89ed27) It was actually an issue with the plugin not the main mod

How rude of me to never respond to this - I don't think I even saw the notification! I know I'm quite late now (and also have moved on from working with Forge modpacks, at least for now), but I figured I'd thank you for going to the effort of discovering and resolving the issue.

I'm no master programmer but I know dev work is difficult and time-consuming and some credit is deserved at least once in a while! 😋
