### ISSUE TITLE
Ceiling torch compat problem

### ISSUE THREAD

**Issue by devmasu** [Yamahari/ILikeWood-1.15#56]
Hi,
I found out that the "Ceiling torch" mod is not compatible with "I like wood". 
Got this error log: 

---- Minecraft Crash Report ----
// My bad.

Time: 5/24/22, 6:45 PM
Description: Rendering overlay

java.lang.IllegalArgumentException: ObjectType[torch] has no registered blocks.
	at yamahari.ilikewood.registry.AbstractILikeWoodObjectRegistry.getRegistryObject(AbstractILikeWoodObjectRegistry.java:49) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at yamahari.ilikewood.registry.AbstractILikeWoodObjectRegistry.getObject(AbstractILikeWoodObjectRegistry.java:60) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at yamahari.ilikewood.ILikeWood.getBlock(ILikeWood.java:92) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at bl4ckscor3.mod.ceilingtorch.compat.ilikewood.WoodenCeilingTorchBlock.lambda$new$0(WoodenCeilingTorchBlock.java:32) ~[ceilingtorch-1.18.2-1.18.jar%2382!/:1.18] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$Properties.lambda$lootFrom$8(BlockBehaviour.java:1026) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_60589_(BlockBehaviour.java:386) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:521) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.25.jar%23187!/:?] {re:mixin}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.25.jar%23187!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.25.jar%23187!/:?] {re:mixin}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.25.jar%23187!/:?] {re:mixin}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$finishModLoading$6(ClientModLoader.java:127) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:113) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.finishModLoading(ClientModLoader.java:127) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$3(ClientModLoader.java:106) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at yamahari.ilikewood.registry.AbstractILikeWoodObjectRegistry.getRegistryObject(AbstractILikeWoodObjectRegistry.java:49) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at yamahari.ilikewood.registry.AbstractILikeWoodObjectRegistry.getObject(AbstractILikeWoodObjectRegistry.java:60) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at yamahari.ilikewood.ILikeWood.getBlock(ILikeWood.java:92) ~[ilikewood-1.18.2-8.5.0.2.jar%23131!/:1.18.2-8.5.0.2] {re:classloading}
	at bl4ckscor3.mod.ceilingtorch.compat.ilikewood.WoodenCeilingTorchBlock.lambda$new$0(WoodenCeilingTorchBlock.java:32) ~[ceilingtorch-1.18.2-1.18.jar%2382!/:1.18] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$Properties.lambda$lootFrom$8(BlockBehaviour.java:1026) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_60589_(BlockBehaviour.java:386) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:521) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.25-universal.jar%23190!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:better_loading_screen-common.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:better_loading_screen-common.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

Could be good to be compatible :D 
Bye

**Comment by bl4ckscor3** [comment]
There is no incompatibility between the mods, you simply have to install the [torches](https://www.curseforge.com/minecraft/mc-mods/i-like-wood-config/files/3722491), [sticks](https://www.curseforge.com/minecraft/mc-mods/i-like-wood-config/files/3722487), and [panels](https://www.curseforge.com/minecraft/mc-mods/i-like-wood-config/files/3722470) config mods from I Like Wood (Torches requires Sticks, which in turn requires Panels). These config mods are now necessary for select content to be enabled in I Like Wood.

**Comment by Yamahari** [comment]
yea, looks like you misconfigured the mod
